---

database:
    type: sqlite
    path: "/tmp/db/metamorph.db"


controller:
    port : 8080

logger:
    path: /tmp/metamorph.log


idrac:
    systemID: "System.Embedded.1"
    managerID: "iDRAC.Embedded.1"
    controllerID: "RAID.Slot.6-1"

templates:
    rootdir: src/bitbucket.com/metamorph
    preseed:
        config:  configs/templates/preseed.tmpl
        filepath: preseed/hwe-ubuntu-server.seed
    grub:
        config:  configs/templates/grub.tmpl
        filepath: grub.conf
    isolinux:
        config: configs/templates/hwe_kernel/isolinux_txt.cfg
    init:
        config: configs/templates/init.sh
        filepath: init.sh
    service:
        config: configs/templates/metamorph-client.service
        filepath: metamorph-client.service
    netplan:
        config: configs/templates/netplan.tmpl
        filepath: 50-cloud-init.yaml
    agent_config:
        config:  templates/agent_config.tmpl
        filepath: agent_config.yaml

assets:
   rootdir: /home/ekuamaj/go/src/bitbucket.com/metamorph/assets
   agent_binary:
          src:  files/metamorph_agent
          dest: metamorph_agent

iso:
  rootpath: /tmp/iso_root
  tempdir: /tmp/iso_root/isos


http:
  rootpath: /tmp/http_root


image:
    url: "http://32.68.220.23:31180/ubuntu-18.04.4-server-amd64.iso"
    checksum: "http://32.68.220.23:31180/ubuntu-18.04.4-server-amd64.iso.md5sum"

provisioning:
    ip : "32.68.220.23"
    port:  3190
    httpport: 31180


testing:
    inputfile: "/home/ekuamaj/go/src/bitbucket.com/metamorph/examples/mtn52r07c001_input.json"

agent:
    node_id: "e415bbbe-be68-4705-aa05-16350e0c8151"
    cntrl_endpoint: "localhost:4040"
    logdir : "/tmp/metamorph"
    temp_dir : "/tmp/metamorph/.tmp"
