---
database:
    type: sqlite
    path: "/tmp/db/metamorph.db"


controller:
    port : 8080

logger:
    path: /tmp/metamorph.log


idrac:
    systemID: "System.Embedded.1"
    managerID: "iDRAC.Embedded.1"
    controllerID: "RAID.Slot.6-1"

templates:
    preseed:
        config:  configs/templates/preseed.tmpl
        filepath:
    grub:
        config:  configs/templates/grub.tmpl
        filepath: 
    isolinux:
        config: configs/templates/hwe_kernel/isolinux_txt.cfg
        filepath:
    init:
        config: configs/templates/init.sh
        filepath:
    service:
        config: configs/templates/metamorph-client.service
        filepath:

iso:
  rootpath: /opt/iso_root

http:
  rootpath: /opt/http_root


image:
    url: "http://32.68.49.133:31180/ubuntu-18.04.3-server-amd64.iso"
    checksum: "http://32.68.49.133:31180/ubuntu-18.04.3-server-amd64.iso.md5sum"