---
database:
    type: sqlite
    path: "/tmp/db/metamorph.db"


controller:
    port : 8080

logger:
    path: /tmp/metamorph.log


idrac:
    systemID: "System.Embedded.1"
    managerID: "iDRAC.Embedded.1"
    controllerID: "RAID.Slot.6-1"
