apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: {{ .Values.namespace }}
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        location / {
                proxy_pass http://{{ include "metamorph.fullname" . }}-api:{{ .Values.serviceMetamorph.port }};
        }
    }
