apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metamorph.fullname" . }}
  labels:
{{ include "metamorph.labels" . | indent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "metamorph.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "metamorph.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: METAMORPH_CONFIGPATH
              value: {{ .Values.metamorphConfigPath }}
          command: [ "/bin/sh", "-c" ]
          args: [ "touch /tmp/metamorph.log; mkdir -p /tmp/iso_root/isos; mkdir -p /tmp/http_root; /metamorph controller; sleep 10; /metamorph api" ]
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: templates-vol
              mountPath: "configs/templates/hwe_kernel/isolinux_txt.cfg"
              subPath: isolinux_txt.cfg
            - name: config-templates
              mountPath: "/configs/templates/metamorph-client.service"
              subPath: metamorph-client.service
            - name: config-templates
              mountPath: "/configs/templates/init.sh"
              subPath: init.sh
            - name: config
              mountPath: "/src/bitbucket.com/metamorph"
      volumes:
        - name: templates-vol
          configMap:
            name: config-templates 
        - name: config
          configMap:
            name: metamorph-config 
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
