apiVersion: v1
kind: Service
metadata:
  name: {{ include "metamorph.fullname" . }}
  labels:
{{ include "metamorph.labels" . | indent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "metamorph.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
